on:
  push:
    paths:
      - 'site/**'
      - '.github/workflows/site.yml'

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # We lint from root which is a bit awkward since we need to install root too
      # TODO: Improve
      - name: Lint
        working-directory: .
        run: npm ci && npm run lint

      - name: Build
        run: npm run build
